# 4个通道 有效测区 索引 范围   4个通道测区索引 对齐    [] 表示全范围
valid_sensor_range: [[11, 241], [3, 233], [3, 233], [2, 232]]
min_threshold: 0.55  # 最小 阈值 (0.4-0.6)   0.5 较合适    能尽可能多的包含小车的响应区

max_zero_num: 0  # 两个 相邻 1 之间 能容忍 最大  0 的个数    ... 1 0 1 ...
min_continuous_one_num: 2  # 响应区域 最少的连1 数量（最少测区数）   小于此值  认为不可能是车的响应区域
min_area_len: 7  # 最小的响应区长度 6  当某个响应区长度 大于 此值时 才需要 划分 车的 数量  否则认为就是一辆车 不需要划分
trough_coefficient: 0.5  # 某波谷 应小于 两旁波峰 最小值的  0.5    才认为 是 有效波谷
fft_index_threshold: 10  # fft 最大值 索引  小于 此值 保留  用作初步筛选

# 波谷阈值  在此范围内  才认为是 有效波谷 也即真正的 多车的分隔点  分多了不行   分少了却是可以的
# 主要考虑大车和大车伴随中间响应区 和值 突然变小形成波谷
min_threshold_trough: 0.08
max_threshold_trough: 0.255

vehicle_type_threshold: 5  # 区分 车型的阈值  大于此值 为 大车(0)  否则为小车(1)      有待商讨


channel_num: 4  # 通道数
channel_disturb_coefficient: 4 #  该值越大  干扰消除  越明显   甚至把大车信号 也会消除
sensor_num_max: 257  # 4个通道中   最大传感器数量    用于标准化  数组   方便numpy数组计算
length_frame: 200  # 每帧 数据 的 长度
slide_length: 200  # 每次 滑动 的长度     若和 帧长相同 相当于 几百个点分析一次  不用滑窗
length_package: 50  # 每包 发送的 帧长

sampleFre: 1000  # 采样频率
send_ip: '127.0.0.1'